[tool]
[tool.poetry]
name = "westac"
version = "0.1.0"
description = "Welfare State Analytics"
authors = ["Roger Mähler <roger.mahler@hotmail.com>"]

[tool.poetry.dependencies]
python = "==3.8.5"
appnope = "*"
attrs = "*"
beakerx = "==1.4.1"
bokeh = "*"
click = "*"
colorcet = "*"
cython = "*"
cytoolz = "*"
decorator = "*"
ftfy = "*"
gensim = "*"
holoviews = "*"
humanfriendly = "*"
ipyaggrid = "*"
ipycytoscape = "*"
ipykernel = "*"
ipympl = "*"
ipywidgets = "*"
joblib = "*"
jupyter-bokeh = "*"
jupyterlab = "*"
lxml = "*"
markdown = "*"
matplotlib = "*"
memoization = "*"
more-itertools = "*"
mypy = "*"
networkx = "*"
nltk = "*"
numba = "*"
numpy = "*"
openpyxl = "*"
pandas = "*"
pandas-bokeh = "*"
py4j = "*"
pydotplus = "*"
pyemd = "*"
python-dotenv = "*"
python-louvain = "*"
scattertext = "*"
scikit-learn = "*"
scipy = "*"
seaborn = "*"
spacy = "==2.3.2"
statsmodels = "*"
textacy = "==0.10.1"
tqdm = "*"
traitlets = "==4.3.3"
wordcloud = "*"
xlrd = "*"
xmltodict = "*"
humlab-penelope = {path = "../../penelope", develop = true}

[tool.poetry.dev-dependencies]
coverage = "*"
dephell = "*"
invoke = "*"
jupytext = "*"
nbstripout = "*"
pre-commit = "*"
pylint = "*"
pytest = "*"
rope = "*"
yapf = "^0.30.0"
black = "^20.8b1"
isort = "^5.5.4"
flake8 = "^3.8.4"
mypy = "^0.782"
pytest-cov = "^2.10.1"
flake8-pytest-style = "^1.3.0"
flake8-black = "^0.2.1"
pyflakes = "^2.2.0"
pycodestyle = "^2.6.0"
pep8-naming = "^0.11.1"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-ra",
    "-q",
    "-s",
]
log_cli = "False"
testpaths = [
    "tests",
]
norecursedirs = ['notebooks', '.git', 'data', 'output', 'deprecated', '__pycache__', 'tmp']
python_files = "*_test.py"
python_functions = "test_*"
filterwarnings = [
#   "ignore",
  "ignore::_pytest.warning_types.PytestCollectionWarning"
]

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "poetry", path = "pyproject.toml"}

[tool.black]
line-length = 120
target-version = ["py38"]
skip-string-normalization = true
# include = '\.pyi?$'
exclude = '''
(
  \.git
  | \.pypy_cache
  | \.pytest_cache
  | \.ipynb_checkpoints
  | deprecated
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort/wiki/isort-Settings
profile = "black"
line_length = 120
py_version = "auto"
float_to_top = true
src_paths = [ "notebooks", "tests" ]
known_first_party = [ "__paths__" ]

[tool.coverage]
# https://github.com/nedbat/coveragepy

    [tool.coverage.run]
    source = ["penelope"]
    branch = true
    omit = ['']

    [tool.coverage.report]
    exclude_lines = [
        "pragma: no cover",
        "raise NotImplementedError"
    ]
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
