[tool]
[tool.poetry]
name = "westac"
version = "0.1.0"
description = "Welfare State Analytics"
authors = ["Roger Mähler <roger.mahler@hotmail.com>"]

[tool.poetry.dependencies]
python = "==3.8.5"
appnope = "*"
attrs = "*"
beakerx = "==1.4.1"
bokeh = "*"
click = "*"
colorcet = "*"
cython = "*"
cytoolz = "*"
decorator = "*"
ftfy = "*"
gensim = "*"
holoviews = "*"
humanfriendly = "*"
ipyaggrid = "*"
ipycytoscape = "*"
ipykernel = "*"
ipympl = "*"
ipywidgets = "*"
joblib = "*"
jupyter-bokeh = "*"
jupyterlab = "*"
lxml = "*"
markdown = "*"
matplotlib = "*"
memoization = "*"
more-itertools = "*"
mypy = "*"
networkx = "*"
nltk = "*"
numba = "*"
numpy = "*"
openpyxl = "*"
pandas = "*"
pandas-bokeh = "*"
py4j = "*"
pydotplus = "*"
pyemd = "*"
python-dotenv = "*"
python-louvain = "*"
scattertext = "*"
scikit-learn = "*"
scipy = "*"
seaborn = "*"
spacy = "==2.3.2"
statsmodels = "*"
textacy = "==0.10.1"
tqdm = "*"
traitlets = "==4.3.3"
wordcloud = "*"
xlrd = "*"
xmltodict = "*"
yapf = "*"
penelope = {path = "../../penelope"}

[tool.poetry.dev-dependencies]
coverage = "*"
dephell = "*"
invoke = "*"
jupytext = "*"
nbstripout = "*"
pre-commit = "*"
pylint = "*"
pytest = "*"
rope = "*"
yapf = "^0.30.0"
black = "^20.8b1"
isort = "^5.5.4"
flake8 = "^3.8.4"
mypy = "^0.782"