version: '3'

services:

  jupyterhub:
    build: jupyterhub
    image: welfare_state_analytics_hub
    container_name: jupyterhub_hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # JupyterHub database and cookie secrets
      - ./jupyterhub_data:/srv/jupyterhub
    env_file:
      - ./jupyterhub/.env
      - ./jupyterhub/secrets/.env.oauth2
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_default"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: welfare_state_analytics
    container_name: welfare_state_analytics-disposable
    network_mode: none
    command: echo

  reverse-proxy:
    image: traefik:1.7
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      #- /etc/letsencrypt/live/westac.humlab.umu.se:/etc/certs:ro
      - /etc/letsencrypt/live/westac.humlab.umu.se/fullchain.pem:/etc/fullchain.pem
      - /etc/letsencrypt/live/westac.humlab.umu.se/privkey.pem:/etc/privkey.pem
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  jupyterhub_data:
