version: '3.2'
services:
  notebook:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: welfare_state_analytics
    # env_file: '.env'
    container_name: welfare_state_analytics
    ports:
      - "8888:8888"
    volumes:
       - type: bind
         source: .
         target: /home/humlab/notebooks
